#Recodificaciones de las variables
#Nuevo nombre base datos: datos_recodificados
datos_recodificados<-datos
datos_recodificados$Nationality<-recode(datos_recodificados$Nationality, 
                                        `1` = "Portugués",
                                        `2` = "Alemán",
                                        `6` = "Español",
                                        `11` = "Italiano",
                                        `13` = "Neerlandés",
                                        `14` = "Inglés",
                                        `17` = "Lituano",
                                        `21` = "Angoleño",
                                        `22` = "Caboverdiano",
                                        `24` = "Guineano",
                                        `25` = "Mozambiqueño",
                                        `26` = "Santotomense",
                                        `32` = "Turco",
                                        `41` = "Brasileño",
                                        `62` = "Rumano",
                                        `100` = "Moldavo (República de Moldavia)",
                                        `101` = "Mexicano",
                                        `103` = "Ucraniano",
                                        `105` = "Ruso",
                                        `108` = "Cubano",
                                        `109` = "Colombiano")


#Course
datos_recodificados$Course<-recode(datos_recodificados$Course, 
                                   `33` = "Tecnologías de Producción de Biocombustibles",
                                   `171` = "Diseño de Animación y Multimedia",
                                   `8014` = "Trabajo Social (turno de tarde)",
                                   `9003` = "Agronomía",
                                   `9070` = "Diseño de Comunicación",
                                   `9085` = "Enfermería Veterinaria",
                                   `9119` = "Ingeniería Informática",
                                   `9130` = "Equinocultura",
                                   `9147` = "Gestión",
                                   `9238` = "Trabajo Social",
                                   `9254` = "Turismo",
                                   `9500` = "Enfermería",
                                   `9556` = "Higiene Bucodental",
                                   `9670` = "Gestión de Publicidad y Marketing",
                                   `9773` = "Periodismo y Comunicación",
                                   `9853` = "Educación Básica",
                                   `9991` = "Gestión (turno de tarde)")
#Mother's Cualification
datos_recodificados$Mother.s.qualification<-recode(datos_recodificados$Mother.s.qualification,
                                                   `1` = "Educación secundaria - 12º año o equivalente",
                                                   `2` = "Educación superior - Grado (Bachelor)",
                                                   `3` = "Educación superior - Grado",
                                                   `4` = "Educación superior - Máster",
                                                   `5` = "Educación superior - Doctorado",
                                                   `6` = "Asistencia a educación superior",
                                                   `9` = "12º año de escolarización - No completado",
                                                   `10` = "11º año de escolarización - No completado",
                                                   `11` = "7º año (antiguo)",
                                                   `12` = "Otro - 11º año de escolarización",
                                                   `14` = "10º año de escolarización",
                                                   `18` = "Curso general de comercio",
                                                   `19` = "Educación básica 3er ciclo (9º/10º/11º año) o equivalente",
                                                   `22` = "Curso técnico-profesional",
                                                   `26` = "7º año de escolarización",
                                                   `27` = "2º ciclo del bachillerato general",
                                                   `29` = "9º año de escolarización - No completado",
                                                   `30` = "8º año de escolarización",
                                                   `34` = "Desconocido",
                                                   `35` = "No sabe leer ni escribir",
                                                   `36` = "Sabe leer sin haber completado 4º año",
                                                   `37` = "Educación básica 1er ciclo (4º/5º año) o equivalente",
                                                   `38` = "Educación básica 2º ciclo (6º/7º/8º año) o equivalente",
                                                   `39` = "Curso de especialización tecnológica",
                                                   `40` = "Educación superior - Grado (1er ciclo)",
                                                   `41` = "Curso de estudios superiores especializados",
                                                   `42` = "Curso técnico superior profesional",
                                                   `43` = "Educación superior - Máster (2º ciclo)",
                                                   `44` = "Educación superior - Doctorado (3er ciclo)")


#Mothers occupation
datos_recodificados$Mother.s.occupation<-recode(datos_recodificados$Mother.s.occupation,
                                                `0` = "Estudiante",
                                                `1` = "Representantes del poder legislativo y ejecutivo, directores y gerentes",
                                                `2` = "Especialistas en actividades intelectuales y científicas",
                                                `3` = "Técnicos y profesiones de nivel intermedio",
                                                `4` = "Personal administrativo",
                                                `5` = "Trabajadores de servicios personales, seguridad y vendedores",
                                                `6` = "Agricultores y trabajadores cualificados en agricultura, pesca y silvicultura",
                                                `7` = "Trabajadores cualificados de la industria, construcción y artesanos",
                                                `8` = "Operadores de instalaciones y maquinaria y trabajadores de montaje",
                                                `9` = "Trabajadores no cualificados",
                                                `10` = "Profesiones de las fuerzas armadas",
                                                `90` = "Otra situación",
                                                `99` = "(en blanco)",
                                                `122` = "Profesionales de la salud",
                                                `123` = "Profesores",
                                                `125` = "Especialistas en tecnologías de la información y la comunicación (TIC)",
                                                `131` = "Técnicos y profesiones intermedias en ciencia e ingeniería",
                                                `132` = "Técnicos y profesionales de nivel intermedio en salud",
                                                `134` = "Técnicos intermedios en servicios jurídicos, sociales, deportivos, culturales y similares",
                                                `141` = "Empleados de oficina, secretarios y operadores de datos",
                                                `143` = "Operadores de datos, contabilidad, estadística, servicios financieros y registros",
                                                `144` = "Otro personal de apoyo administrativo",
                                                `151` = "Trabajadores de servicios personales",
                                                `152` = "Vendedores",
                                                `153` = "Trabajadores de cuidado personal y similares",
                                                `171` = "Trabajadores cualificados de la construcción (excepto electricistas)",
                                                `173` = "Trabajadores cualificados en impresión, instrumentos de precisión, joyería y artesanía",
                                                `175` = "Trabajadores en procesamiento de alimentos, madera, textil y otras industrias",
                                                `191` = "Trabajadores de limpieza",
                                                `192` = "Trabajadores no cualificados en agricultura, pesca y silvicultura",
                                                `193` = "Trabajadores no cualificados en industria extractiva, construcción, manufactura y transporte",
                                                `194` = "Ayudantes de preparación de comidas")


datos_recodificados$Father.s.occupation<-recode(datos_recodificados$Father.s.occupation,
                                                `0` = "Estudiante",
                                                `1` = "Representantes del poder legislativo y ejecutivo, directores y gerentes",
                                                `2` = "Especialistas en actividades intelectuales y científicas",
                                                `3` = "Técnicos y profesiones de nivel intermedio",
                                                `4` = "Personal administrativo",
                                                `5` = "Trabajadores de servicios personales, seguridad y vendedores",
                                                `6` = "Agricultores y trabajadores cualificados en agricultura, pesca y silvicultura",
                                                `7` = "Trabajadores cualificados de la industria, construcción y artesanos",
                                                `8` = "Operadores de instalaciones y maquinaria y trabajadores de montaje",
                                                `9` = "Trabajadores no cualificados",
                                                `10` = "Profesiones de las fuerzas armadas",
                                                `90` = "Otra situación",
                                                `99` = "(en blanco)",
                                                `101` = "Oficiales de las fuerzas armadas",
                                                `102` = "Sargentos de las fuerzas armadas",
                                                `103` = "Otro personal de las fuerzas armadas",
                                                `112` = "Directores de servicios administrativos y comerciales",
                                                `114` = "Directores de hostelería, comercio y otros servicios",
                                                `121` = "Especialistas en ciencias físicas, matemáticas, ingeniería y afines",
                                                `122` = "Profesionales de la salud",
                                                `123` = "Profesores",
                                                `124` = "Especialistas en finanzas, contabilidad, organización administrativa y relaciones públicas/comerciales",
                                                `131` = "Técnicos y profesiones intermedias en ciencia e ingeniería",
                                                `132` = "Técnicos y profesionales de nivel intermedio en salud",
                                                `134` = "Técnicos intermedios en servicios jurídicos, sociales, deportivos y culturales",
                                                `135` = "Técnicos en tecnologías de la información y la comunicación",
                                                `141` = "Empleados de oficina, secretarios y operadores de datos",
                                                `143` = "Operadores de datos, contabilidad, estadística, servicios financieros y registros",
                                                `144` = "Otro personal de apoyo administrativo",
                                                `151` = "Trabajadores de servicios personales",
                                                `152` = "Vendedores",
                                                `153` = "Trabajadores de cuidado personal y similares",
                                                `154` = "Personal de protección y seguridad",
                                                `161` = "Agricultores orientados al mercado y trabajadores cualificados agrícolas y ganaderos",
                                                `163` = "Agricultores, ganaderos, pescadores, cazadores y recolectores de subsistencia",
                                                `171` = "Trabajadores cualificados de la construcción (excepto electricistas)",
                                                `172` = "Trabajadores cualificados en metalurgia y metal",
                                                `174` = "Trabajadores cualificados en electricidad y electrónica",
                                                `175` = "Trabajadores en procesamiento de alimentos, madera, textil y otras industrias",
                                                `181` = "Operadores de instalaciones y maquinaria fija",
                                                `182` = "Trabajadores de montaje",
                                                `183` = "Conductores de vehículos y operadores de maquinaria móvil",
                                                `192` = "Trabajadores no cualificados en agricultura, pesca y silvicultura",
                                                `193` = "Trabajadores no cualificados en industria extractiva, construcción, manufactura y transporte",
                                                `194` = "Ayudantes de preparación de comidas",
                                                `195` = "Vendedores ambulantes (excepto alimentos) y proveedores de servicios en la calle")

datos_recodificados$Father.s.occupation<-recode(datos_recodificados$Father.s.occupation,
                                                `0` = "Estudiante",
                                                `1` = "Representantes del poder legislativo y ejecutivo, directores y gerentes",
                                                `2` = "Especialistas en actividades intelectuales y científicas",
                                                `3` = "Técnicos y profesiones de nivel intermedio",
                                                `4` = "Personal administrativo",
                                                `5` = "Trabajadores de servicios personales, seguridad y vendedores",
                                                `6` = "Agricultores y trabajadores cualificados en agricultura, pesca y silvicultura",
                                                `7` = "Trabajadores cualificados de la industria, construcción y artesanía",
                                                `8` = "Operadores de instalaciones y maquinaria y trabajadores de montaje",
                                                `9` = "Trabajadores no cualificados",
                                                `10` = "Profesiones de las fuerzas armadas",
                                                `90` = "Otra situación",
                                                `99` = "(en blanco)",
                                                `101` = "Oficiales de las fuerzas armadas",
                                                `102` = "Sargentos de las fuerzas armadas",
                                                `103` = "Otro personal de las fuerzas armadas",
                                                `112` = "Directores de servicios administrativos y comerciales",
                                                `114` = "Directores de hostelería, comercio y otros servicios",
                                                `121` = "Especialistas en ciencias físicas, matemáticas, ingeniería y afines",
                                                `122` = "Profesionales de la salud",
                                                `123` = "Profesores",
                                                `124` = "Especialistas en finanzas, contabilidad, organización administrativa y relaciones públicas/comerciales",
                                                `131` = "Técnicos intermedios en ciencia e ingeniería",
                                                `132` = "Técnicos y profesionales intermedios de salud",
                                                `134` = "Técnicos intermedios en servicios jurídicos, sociales, deportivos y culturales",
                                                `135` = "Técnicos en tecnologías de la información y la comunicación",
                                                `141` = "Empleados de oficina, secretarios y operadores de datos",
                                                `143` = "Operadores de datos, contabilidad, estadística y servicios financieros",
                                                `144` = "Otro personal de apoyo administrativo",
                                                `151` = "Trabajadores de servicios personales",
                                                `152` = "Vendedores",
                                                `153` = "Trabajadores de cuidado personal y similares",
                                                `154` = "Personal de protección y seguridad",
                                                `161` = "Agricultores orientados al mercado y trabajadores agrícolas cualificados",
                                                `163` = "Agricultores de subsistencia, pescadores, cazadores y recolectores",
                                                `171` = "Trabajadores cualificados de la construcción (excepto electricistas)",
                                                `172` = "Trabajadores cualificados en metalurgia y trabajo del metal",
                                                `174` = "Trabajadores cualificados en electricidad y electrónica",
                                                `175` = "Trabajadores en alimentación, madera, textil y otras industrias",
                                                `181` = "Operadores de instalaciones y maquinaria fija",
                                                `182` = "Trabajadores de montaje",
                                                `183` = "Conductores de vehículos y operadores de maquinaria móvil",
                                                `192` = "Trabajadores no cualificados en agricultura, pesca y silvicultura",
                                                `193` = "Trabajadores no cualificados en industria, construcción y transporte",
                                                `194` = "Ayudantes de preparación de comidas",
                                                `195` = "Vendedores ambulantes (excepto alimentos) y servicios callejeros")


datos_recodificados$Displaced<-recode(datos_recodificados$Displaced,
                                      `1` = "Sí",
                                      `0` = "No")

datos_recodificados$Educational.special.needs<-recode(datos_recodificados$Educational.special.needs,
                                                      `1` = "Sí",
                                                      `0` = "No")
datos_recodificados$Debtor<-recode(datos_recodificados$Debtor,
                                   `1` = "Sí",
                                   `0` = "No")
datos_recodificados$Tuition.fees.up.to.date<-recode(datos_recodificados$Tuition.fees.up.to.date,
                                                    `1` = "Sí",
                                                    `0` = "No")
datos_recodificados$International<-recode(datos_recodificados$International,
                                          `1` = "Sí",
                                          `0` = "No")

datos_recodificados$Gender<-recode(datos_recodificados$Gender,
                                   `1` = "Sí",
                                   `0` = "No")
datos_recodificados$Scholarship.holder<-recode(datos_recodificados$Scholarship.holder,
                                               `1` = "Sí",
                                               `0` = "No")

datos_recodificados$Marital.status<-recode(datos_recodificados$Marital.status,
                                           `1` = "Soltero",
                                           `2` = "Casado",
                                           `3` = "Viudo",
                                           `4` = "Divorciado",
                                           `5` = "Con pareja",
                                           `6` = "Separado legalmente"
)

datos_recodificados$Application.mode<-recode(datos_recodificados$Application.mode,
                                             `1` = "1ª fase - cupo general",
                                             `2` = "Ordenanza nº 612/93",
                                             `5` = "1ª fase - cupo especial (Islas Azores)",
                                             `7` = "Titulares de otros estudios superiores",
                                             `10` = "Ordenanza nº 854-B/99",
                                             `15` = "Estudiante internacional (grado)",
                                             `16` = "1ª fase - cupo especial (Isla de Madeira)",
                                             `17` = "2ª fase - cupo general",
                                             `18` = "3ª fase - cupo general",
                                             `26` = "Ordenanza nº 533-A/99, apartado b2 (plan diferente)",
                                             `27` = "Ordenanza nº 533-A/99, apartado b3 (otra institución)",
                                             `39` = "Mayores de 23 años",
                                             `42` = "Traslado",
                                             `43` = "Cambio de titulación",
                                             `44` = "Titulares de diploma de especialización tecnológica",
                                             `51` = "Cambio de institución/titulación",
                                             `53` = "Titulares de diploma de ciclo corto",
                                             `57` = "Cambio de institución/titulación (internacional)"
)
datos_recodificados$Previous.qualification<-recode(datos_recodificados$Previous.qualification,
                                                   `1` = "Educación secundaria",
                                                   `2` = "Educación superior - grado (bachelor)",
                                                   `3` = "Educación superior - grado",
                                                   `4` = "Educación superior - máster",
                                                   `5` = "Educación superior - doctorado",
                                                   `6` = "Asistencia a educación superior",
                                                   `9` = "12º curso - no completado",
                                                   `10` = "11º curso - no completado",
                                                   `12` = "Otro - 11º curso",
                                                   `14` = "10º curso",
                                                   `15` = "10º curso - no completado",
                                                   `19` = "Educación básica 3er ciclo (9º/10º/11º) o equivalente",
                                                   `38` = "Educación básica 2º ciclo (6º/7º/8º) o equivalente",
                                                   `39` = "Curso de especialización tecnológica",
                                                   `40` = "Educación superior - grado (1er ciclo)",
                                                   `42` = "Curso técnico superior profesional",
                                                   `43` = "Educación superior - máster (2º ciclo)")
datos_recodificados$Daytime.evening.attendance.<-recode(datos_recodificados$Daytime.evening.attendance.,
                                                        `1` = "Mañana",
                                                        `0` = "Tarde")
#datos_recodificados$NOMBREVARIABLE0<-recode(datos_recodificados$NOMBREVARIABLE0,)
